### ISSUE TITLE
Parallel FaIR

### ISSUE THREAD

**Issue by chrisroadmap** [openscm/openscm-runner#42]
Even at 12 ensemble members per second, running 1600 scenarios x 2237 ensemble members is going to take a long time (>3 days). In my Working Group 1 setup with FaIR I use `multiprocessing.Pool` to parallelise things. Does MAGICC do something different here, and is there a preferred method I should use?

Once this method is down it should be relatively simple to get `openscm-twolayermodel` for low effort cost.

**Comment by znicholls** [comment]
MAGICC does something different but only because it has an on-disk binary. Simply using `multiprocessing.Pool` (and then calling `.map` I guess) here would be perfect!

**Comment by znicholls** [comment]
I guess you just turn this loop https://github.com/openscm/openscm-runner/blob/49bd5f533fc56c6554823c2b309d51e933a28449/src/openscm_runner/adapters/fair_adapter/_run_fair.py#L34 into pool.map and off you go

**Comment by chrisroadmap** [comment]
Yeah with a bit of fiddling I think I've got it
