### ISSUE TITLE
numpy.float deprecated but still used by the cicero-scm

### ISSUE THREAD

**Issue by jkikstra** [openscm/openscm-runner#81]
**Describe the bug**

The cicero-scm workflow test started failing since numpy has been updated to 1.21+, which has deprecated `np.float` for the builtin `float`.

See: https://github.com/iiasa/climate-assessment/pull/26

After a quick look, it seems like this line may be the [single](https://github.com/openscm/openscm-runner/search?q=np.float) offender: https://github.com/openscm/openscm-runner/blob/b4c6fa0f37d1c5b61035926a8e45deb6f6064ddf/src/openscm_runner/adapters/utils/cicero_utils/make_scenario_common.py#L228

**Comment by maritsandstad** [comment]
I'll look at and fix the ciceroscm usage today...

**Comment by maritsandstad** [comment]
Sorry, it seems you already fixed this...?

**Comment by jkikstra** [comment]
Hi @maritsandstad thanks - yes I just woke up to and seems like @lewisjared has merged it with #82 and updated it to the changelog!

So this one can be closed
